-- TUSER
CREATE TABLE PUBLIC.TUSER(USER_ VARCHAR(50) NOT NULL PRIMARY KEY,PASSWORD VARCHAR(255),NAME VARCHAR(50),SURNAME VARCHAR(50),EMAIL VARCHAR(50),NIF VARCHAR(50),USERBLOCKED TIMESTAMP,LASTPASSWORDUPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FIRSTLOGIN BOOLEAN DEFAULT TRUE);
INSERT INTO TUSER VALUES('demo','demouser','demo','demo',NULL,'44460713B',NULL,NULL,NULL);
INSERT INTO TUSER VALUES('prueba','prueba','prueba','prueba',NULL,'44460713B',NULL,NULL,NULL);


-- TROLE
CREATE TABLE PUBLIC.TROLE(ID_ROLENAME SERIAL NOT NULL PRIMARY KEY,ROLENAME VARCHAR(255),XMLCLIENTPERMISSION VARCHAR(10485760));
INSERT INTO TROLE VALUES(0,'admin','<?xml version="1.0" encoding="UTF-8"?><security></security>');


-- TUSER_ROLE
CREATE TABLE PUBLIC.TUSER_ROLE(ID_USER_ROLE SERIAL NOT NULL PRIMARY KEY,ID_ROLENAME INTEGER,USER_ VARCHAR(50),CONSTRAINT FK_TUSER FOREIGN KEY(USER_) REFERENCES PUBLIC.TUSER(USER_),CONSTRAINT FK_TROLE FOREIGN KEY(ID_ROLENAME) REFERENCES PUBLIC.TROLE(ID_ROLENAME));
INSERT INTO TUSER_ROLE VALUES(0,0,'demo');
INSERT INTO TUSER_ROLE VALUES(1,0,'prueba');


-- TSERVER_PERMISSION
CREATE TABLE PUBLIC.TSERVER_PERMISSION(ID_SERVER_PERMISSION SERIAL NOT NULL PRIMARY KEY,PERMISSION_NAME VARCHAR(10485760));
INSERT INTO TSERVER_PERMISSION VALUES(0,'com.ontimize.jee.common.services.user.IUserInformationService/getUserInformation');

-- TROLE_SERVER
CREATE TABLE PUBLIC.TROLE_SERVER_PERMISSION(ID_ROLE_SERVER_PERMISSION SERIAL NOT NULL PRIMARY KEY,ID_ROLENAME INTEGER,ID_SERVER_PERMISSION INTEGER,CONSTRAINT FK_TROLE_SERVER_PERMISSION FOREIGN KEY(ID_ROLENAME) REFERENCES PUBLIC.TROLE(ID_ROLENAME),CONSTRAINT FK_TSERVER_PERMISSION FOREIGN KEY(ID_SERVER_PERMISSION) REFERENCES PUBLIC.TSERVER_PERMISSION(ID_SERVER_PERMISSION));
INSERT INTO TROLE_SERVER_PERMISSION VALUES(0,0,0);

-- TSETTING
CREATE TABLE PUBLIC.TSETTING(ID_SETTING SERIAL NOT NULL PRIMARY KEY,SETTING_KEY VARCHAR(10485760),SETTING_VALUE VARCHAR(10485760),SETTING_COMMENT VARCHAR(10485760));
INSERT INTO TSETTING VALUES(0,'mail_host','smtp.gmail.com','Host del servidor');
INSERT INTO TSETTING VALUES(1,'mail_port','587','Puerto del servidor de email');
INSERT INTO TSETTING VALUES(2,'mail_protocol','smtp','Protocolo de env\u005cu00edo de mails');
INSERT INTO TSETTING VALUES(3,'mail_user','mi.mail@example.com','Usuario para el env\u005cu00edo de mails');
INSERT INTO TSETTING VALUES(4,'mail_password','mis_credenciales','Password del servidor de mail');
INSERT INTO TSETTING VALUES(5,'mail_encoding','UTF-8','Codificaci\u005cu00f3n de mails');
INSERT INTO TSETTING VALUES(6,'mail_properties','mail.smtp.auth:true;mail.smtp.starttls.enable:true;','Propiedades de mails');
INSERT INTO TSETTING VALUES(7,'report_folder','C:/applications/ontimize-boot-app/reports','Carpeta de las plantillas de report');

-- TUSER_PREFERENCE
CREATE TABLE PUBLIC.TUSER_PREFERENCE(ID_USER_PREFERENCE SERIAL NOT NULL PRIMARY KEY,PREFERENCE_NAME VARCHAR(150),USER_LOGIN VARCHAR(150),PREFERENCE_VALUE VARCHAR(10485760));
INSERT INTO TUSER_PREFERENCE VALUES(0,'user_preference','demo','Iw0KI1R1ZSBNYXkgMTYgMTI6NTc6MDYgQ0VTVCAyMDE3DQpkZW1vX2FwcF9zdGF0dXNfYmFyX3Zpc2libGU9eWVzDQpkZW1vX2FkanVzdF90cmVlX3NwYWNlPXRydWUNCmRlbW9fYXBwX3dpbmRvd19zdGF0ZT0wDQpkZW1vX3RhYmxlX2NvbmZfc29ydF9maWx0ZXJfZm9ybUN1c3RvbWVyLnhtbF9DdXN0b21lclNlcnZpY2UuY3VzdG9tZXJfVEVTVD1udWxsO251bGw7U1VSTkFNRVw9OThcOjF8SURcPTc1XDoyfE5BTUVcPTk5XDozfENVU1RPTUVSVFlQRUlEXD0wXDo0fENVU1RPTUVSSURcPTEyNVw6NXxBRERSRVNTXD0xMjNcOjZ8UEhPTkVcPTEyMVw6N3xTVEFSVERBVEVcPTEzNlw6OHxMT05HSVRVREVcPTExNlw6OXxMQVRJVFVERVw9MTEzXDoxMHxFTUFJTFw9MTcwXDoxMnw7QkFTRTY0ck8wQUJYTnlBQk5xWVhaaExuVjBhV3d1U0dGemFIUmhZbXhsRTdzUEpTRks1TGdEQUFKR0FBcHNiMkZrUm1GamRHOXlTUUFKZEdoeVpYTm9iMnhrZUhBL1FBQUFBQUFBQ0hjSUFBQUFDd0FBQUFCNA0KZGVtb190YWJsZV9jb25mX3NvcnRfZmlsdGVyX2NvbmZpZ3VyYXRpb25zX2Zvcm1DdXN0b21lci54bWxfQ3VzdG9tZXJTZXJ2aWNlLmN1c3RvbWVyPVRFU1QNCmRlbW9fdGFibGVfY29udHJvbF9wYW5lbF9mb3JtQWNjb3VudHMtZGV0YWlsLnhtbF9Nb3ZlbWVudFNlcnZpY2UubW92ZW1lbnQ9Z3JvdXB0YWJsZWtleTtkZWZhdWx0Y2hhcnRidXR0b247ZXhjZWxleHBvcnRidXR0b247c3Vtcm93YnV0dG9uO2NhbGN1bGVkY29sc2J1dHRvbjtwcmludGluZ2J1dHRvbjtmaWx0ZXJzYXZlYnV0dG9uO3Zpc2libGVjb2xzYnV0dG9uO2h0bWxleHBvcnRidXR0b247Y29weWJ1dHRvbjtncm91cHRhYmxla2V5O2luc2VydGJ1dHRvbjtyZWZyZXNoYnV0dG9uDQpkZW1vX2Zvcm1CcmFuY2hlcy1kZXRhaWwueG1sPTg4MDs1MDU7LTExNTA7MzY5DQpkZW1vX2RldGFpbF9kaWFsb2dfc2l6ZV9wb3NpdGlvbl9mb3JtQ3VzdG9tZXIueG1sX0N1c3RvbWVyU2VydmljZS5jdXN0b21lcj03NDk7MzUwOy0xOTA1OzM5MQ0KZGVtb19hcHBfdG9vbGJhcl9sb2NhdGlvbj1Ob3J0aA0KZGVtb19hcHBfd2luZG93X3Bvc2l0aW9uPS0xNTgwOzExDQpkZW1vX2FwcF93aW5kb3dfc2l6ZT0xNTg0OzEwNDQNCmRlbW9fZm9ybUVtcGxveWVlcy1kZXRhaWwueG1sPTExMTY7NzM5OzYxMDsxOTUNCmRlbW9fZm9ybUFjY291bnRzLWRldGFpbC54bWw9OTE1OzUwMDstMTE1MDszNjkNCg==');

-- TI18N
CREATE TABLE PUBLIC.TI18N(ID_I18N SERIAL NOT NULL PRIMARY KEY,CLASS_NAME VARCHAR(150),I18N_DESCRIPTION VARCHAR(250));
INSERT INTO TI18N VALUES(0,'i18n.bundle','Resource bundle in database');

-- PILOTS
CREATE TABLE PILOTS (
	IDPILOT SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(50),
	SURNAME VARCHAR(100),
	TEAM VARCHAR(50)
);

INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Lewis', 'Hamilton', 'Mercedes');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('George', 'Russell', 'Mercedes');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Esteban', 'Ocon', 'Alpine');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Pierre', 'Gasly', 'Alpine');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Nico', 'Hulkenberg', 'Haas');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Kevin', 'Magnussen', 'Haas');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Lando', 'Norris', 'McLaren');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Oscar', 'Piastri', 'McLaren');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Max', 'Verstappen', 'Red Bull');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Sergio', 'Perez', 'Red Bull');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Fernando', 'Alonso', 'Aston Martin');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Lance', 'Stroll', 'Aston Martin');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Yuki', 'Tsunoda', 'Alphatauri');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Nyck', 'De Vries', 'Alphatauri');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Charles', 'Leclerc', 'Ferrari');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Carlos', 'Sainz', 'Ferrari');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Valtteri', 'Bottas', 'Alfa Romeo');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Guanyu', 'Zhou', 'Alfa Romeo');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Alexander', 'Albon', 'Williams');
INSERT INTO PILOTS (NAME, SURNAME, TEAM) values ('Logan', 'Sargeant', 'Williams');

-- USERS
CREATE TABLE PUBLIC.USERS(
	USER_ID SERIAL NOT NULL PRIMARY KEY,
	USER_ VARCHAR(50),
	PASSWORD VARCHAR(255),
	NAME VARCHAR(50),
	SURNAME VARCHAR(50),
	EMAIL VARCHAR(50));

INSERT INTO USERS (USER_, PASSWORD, EMAIL, NAME, SURNAME ) VALUES ('demo', 'demouser', 'geo@gmail.com', 'David', 'Andares');
INSERT INTO USERS (USER_, PASSWORD, EMAIL, NAME, SURNAME ) VALUES ('prueba', 'prueba', 'peli@gmail.com', 'Cesar', 'Seoane');
INSERT INTO USERS (USER_, PASSWORD, EMAIL, NAME, SURNAME ) VALUES ('geo', 123, 'geo@gmail.com', 'David', 'Andares');
INSERT INTO USERS (USER_, PASSWORD, EMAIL, NAME, SURNAME ) VALUES ('peli', 123, 'peli@gmail.com', 'Cesar', 'Seoane');
INSERT INTO USERS (USER_, PASSWORD, EMAIL, NAME, SURNAME ) VALUES ('lula', 123, 'lula@gmail.com', 'Gaia', 'Sorre');

-- COMPETITIONS
CREATE TABLE COMPETITIONS(
	COMP_ID SERIAL PRIMARY KEY, 
	COMP_NAME VARCHAR(255), 
	COMP_TYPE VARCHAR(255), 
	COMP_DESCRIPTION VARCHAR(500)
);

INSERT INTO public.COMPETITIONS (COMP_NAME, COMP_TYPE, COMP_DESCRIPTION) VALUES('LIGUILLA PEPITO', 'PUBLIC', '');
INSERT INTO public.COMPETITIONS (COMP_NAME, COMP_TYPE, COMP_DESCRIPTION) VALUES('FREIXO LEAGUE', 'PUBLIC', '');
INSERT INTO public.COMPETITIONS (COMP_NAME, COMP_TYPE, COMP_DESCRIPTION) VALUES('OS VACALOURAS', 'PUBLIC', '');

--- USER_COMPETITION

CREATE TABLE USER_COMPETITION (
	UC_ID SERIAL PRIMARY KEY, 
	UC_COMP_ID SERIAL, 
	UC_USER_ID VARCHAR(50));

ALTER TABLE USER_COMPETITION
   ADD CONSTRAINT FK_UC_COMP_ID
   FOREIGN KEY (UC_COMP_ID)
   REFERENCES COMPETITIONS(COMP_ID);

ALTER TABLE USER_COMPETITION
   ADD CONSTRAINT FK_UC_USER_ID
   FOREIGN KEY (UC_USER_ID)
   REFERENCES TUSER(USER_);


